replicaCount: 2
config:
  environment: dev
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: true
image:
  tag: "7c17f504bf42eb5fd5f1acf1f3a2b9606d304021"