replicaCount: 2
config:
  environment: dev
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: true
image:
  tag: "480859bc9c0340d6d0b11402bad153b53b592773"