replicaCount: 2
config:
  environment: dev
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: true
image:
  tag: "66c9ccdd4726e860698d7b2514d449624359d08d"