apiVersion: v1
kind: Service
metadata:
  name: featureboard
  labels:
    app: featureboard          # po tej etykiecie znajdzie nas ServiceMonitor
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: featureboard
  ports:
    - name: http               # ServiceMonitor wskazuje port PO NAZWIE
      port: {{ .Values.service.port }}
      targetPort: 8000