apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: featureboard-dev
  namespace: argocd               # obiekty Application żyją w namespace argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Explotion80/featureboard.git
    targetRevision: main          # śledź gałąź main
    path: k8s/featureboard        # nasz chart
    helm:
      valueFiles:
        - ../values-dev.yaml       # nakładka dev (ścieżka względem path)
  destination:
    server: https://kubernetes.default.svc   # ten sam klaster, w którym żyje Argo
    namespace: featureboard
  syncPolicy:
    automated:
      prune: true                  # usuń z klastra to, co zniknęło z gita
      selfHeal: true               # cofnij ręczne zmiany na klastrze
    syncOptions:
      - CreateNamespace=true