apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "87.10.1"    # przypinamy, jak wszystko
    helm:
      values: |
        grafana:
          enabled: true          
        alertmanager:
          enabled: false          
        coreDns:
          enabled: false          
        prometheus:
          prometheusSpec:
            retention: 24h        # krótka historia — oszczędza dysk/RAM (dev)
            resources:
              requests:
                cpu: 100m
                memory: 400Mi
              limits:
                memory: 900Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      # CRD Prometheusa są wielkie (jak ApplicationSet w Argo)